// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace MCA_EF_API.Domain.Entities.Configurations
{
    public partial class ChecklistTypeUnitTypeConfiguration : IEntityTypeConfiguration<ChecklistTypeUnitType>
    {
        public void Configure(EntityTypeBuilder<ChecklistTypeUnitType> entity)
        {
            entity.ToTable("ChecklistType_UnitType", "dbo");

            entity.HasOne(d => d.ChecklistType)
                .WithMany(p => p.ChecklistTypeUnitType)
                .HasForeignKey(d => d.ChecklistTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChecklistType_UnitType_ChecklistType");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ChecklistTypeUnitType> entity);
    }
}
