// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace MCA_EF_API.Domain.Entities.Configurations
{
    public partial class ChecklistTypeConfiguration : IEntityTypeConfiguration<ChecklistType>
    {
        public void Configure(EntityTypeBuilder<ChecklistType> entity)
        {
            entity.ToTable("ChecklistType", "dbo");

            entity.Property(e => e.Icon)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Label)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.ChecklistAreaNavigation)
                .WithMany(p => p.ChecklistType)
                .HasForeignKey(d => d.ChecklistArea)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChecklistType_ChecklistType");

            entity.HasOne(d => d.ChecklistFrequencyNavigation)
                .WithMany(p => p.ChecklistType)
                .HasForeignKey(d => d.ChecklistFrequency)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChecklistType_ChecklistFrequency");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ChecklistType> entity);
    }
}
