// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace MCA_EF_API.Domain.Entities.Configurations
{
    public partial class FormElementOptionConfiguration : IEntityTypeConfiguration<FormElementOption>
    {
        public void Configure(EntityTypeBuilder<FormElementOption> entity)
        {
            entity.ToTable("FormElement_Option", "DynamicForms");

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.HoverText)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.Label)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.FormElement)
                .WithMany(p => p.FormElementOption)
                .HasForeignKey(d => d.FormElementId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FormElement_Option_FormElement");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FormElementOption> entity);
    }
}
