// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace MCA_EF_API.Domain.Entities.Configurations
{
    public partial class FormElementTypeAssetConfiguration : IEntityTypeConfiguration<FormElementTypeAsset>
    {
        public void Configure(EntityTypeBuilder<FormElementTypeAsset> entity)
        {
            entity.ToTable("FormElement_TypeAsset", "DynamicForms");

            entity.HasOne(d => d.FormElement)
                .WithMany(p => p.FormElementTypeAsset)
                .HasForeignKey(d => d.FormElementId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FormElement_TypeAsset_FormElement");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FormElementTypeAsset> entity);
    }
}
