// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace MCA_EF_API.Domain.Entities.Configurations
{
    public partial class NestedFormSectionConfiguration : IEntityTypeConfiguration<NestedFormSection>
    {
        public void Configure(EntityTypeBuilder<NestedFormSection> entity)
        {
            entity.ToTable("NestedFormSection", "DynamicForms");

            entity.HasOne(d => d.ParentFormSection)
                .WithMany(p => p.NestedFormSection)
                .HasForeignKey(d => d.ParentFormSectionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_NestedFormSection_FormSection");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<NestedFormSection> entity);
    }
}
