// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace MCA_EF.Data.Entities
{
    public partial class ChecklistType
    {
        public ChecklistType()
        {
            ChecklistTypeUnitType = new HashSet<ChecklistTypeUnitType>();
        }

        public int ChecklistTypeId { get; set; }
        public int ChecklistArea { get; set; }
        public int ChecklistFrequency { get; set; }
        public Guid FormExternalId { get; set; }
        public string Label { get; set; }
        public string Icon { get; set; }
        public bool IsActive { get; set; }

        public virtual ChecklistArea ChecklistAreaNavigation { get; set; }
        public virtual ChecklistFrequency ChecklistFrequencyNavigation { get; set; }
        public virtual ICollection<ChecklistTypeUnitType> ChecklistTypeUnitType { get; set; }
    }
}