// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace MCA_EF.Data.Entities
{
    public partial class ChecklistFrequency
    {
        public ChecklistFrequency()
        {
            ChecklistType = new HashSet<ChecklistType>();
        }

        public int ChecklistFrequencyId { get; set; }
        public string Label { get; set; }

        public virtual ICollection<ChecklistType> ChecklistType { get; set; }
    }
}