// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace MCA_EF.Data.Entities
{
    public partial class FormElementResponse
    {
        public FormElementResponse()
        {
            ResponseValue = new HashSet<ResponseValue>();
        }

        public int FormElementResponseId { get; set; }
        public int FormResponseId { get; set; }
        public int FormElementId { get; set; }
        public int? FormSectionId { get; set; }
        public int DisplayRowIndex { get; set; }
        public int DisplayColumnIndex { get; set; }

        public virtual FormElement FormElement { get; set; }
        public virtual FormResponse FormResponse { get; set; }
        public virtual FormSection FormSection { get; set; }
        public virtual ICollection<ResponseValue> ResponseValue { get; set; }
    }
}