// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace MCA_EF.Data.Entities
{
    public partial class FormElementOption : IAuditable
    {
        public FormElementOption()
        {
            FormElementDependsOnRule = new HashSet<FormElementDependsOnRule>();
        }

        public int FormElementOptionId { get; set; }
        public int FormElementId { get; set; }
        public string Label { get; set; }
        public bool IsActive { get; set; }
        public string HoverText { get; set; }
        public DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public int DisplayIndex { get; set; }

        public virtual FormElement FormElement { get; set; }
        public virtual ICollection<FormElementDependsOnRule> FormElementDependsOnRule { get; set; }
    }
}