// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace MCA_EF.Data.Entities
{
    public partial class FormResponse : IAuditable
    {
        public FormResponse()
        {
            FormElementResponse = new HashSet<FormElementResponse>();
        }

        public int FormResponseId { get; set; }
        public Guid FormResponseExternalId { get; set; }
        public int CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public int FormId { get; set; }

        public virtual Person CreatedByNavigation { get; set; }
        public virtual Form Form { get; set; }
        public virtual ICollection<FormElementResponse> FormElementResponse { get; set; }
    }
}