// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace MCA_EF.Data.Entities
{
    public partial class FormElementDependsOnRule
    {
        public int FormElementDependsOnRuleId { get; set; }
        public int SubjectFormElementId { get; set; }
        public int PredicateFormElementId { get; set; }
        public int OperatorId { get; set; }
        public int? OptionId { get; set; }
        public bool IsRequiredIfConditionMet { get; set; }
        public bool IsDisplayedOnlyIfConditionMet { get; set; }
        public bool BaseValuesOnPredicateValue { get; set; }

        public virtual Operator Operator { get; set; }
        public virtual FormElementOption Option { get; set; }
        public virtual FormElement SubjectFormElement { get; set; }
    }
}