// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace MCA_EF.Data.Entities
{
    public partial class Operator
    {
        public Operator()
        {
            FormElementDependsOnRule = new HashSet<FormElementDependsOnRule>();
            FormElementValidator = new HashSet<FormElementValidator>();
        }

        public int OperatorId { get; set; }
        public string Label { get; set; }
        public string Description { get; set; }

        public virtual ICollection<FormElementDependsOnRule> FormElementDependsOnRule { get; set; }
        public virtual ICollection<FormElementValidator> FormElementValidator { get; set; }
    }
}