// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace MCA_EF.Data.Entities
{
    public partial class Person
    {
        public Person()
        {
            Form = new HashSet<Form>();
            FormResponse = new HashSet<FormResponse>();
            FormSection = new HashSet<FormSection>();
        }

        public int PersonId { get; set; }
        public string LanId { get; set; }
        public string Email { get; set; }

        public virtual ICollection<Form> Form { get; set; }
        public virtual ICollection<FormResponse> FormResponse { get; set; }
        public virtual ICollection<FormSection> FormSection { get; set; }
    }
}