// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace MCA_EF.Data.Entities
{
    public partial class ResponseValue
    {
        public int ResponseValueId { get; set; }
        public int FormElementResponseId { get; set; }
        public string TextValue { get; set; }
        public int? OptionId { get; set; }

        public virtual FormElementResponse FormElementResponse { get; set; }
    }
}