// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace MCA_EF.Data.Entities
{
    public partial class TypeValidator
    {
        public TypeValidator()
        {
            FormElementValidator = new HashSet<FormElementValidator>();
        }

        public int TypeValidatorId { get; set; }
        public string Label { get; set; }
        public string Description { get; set; }

        public virtual ICollection<FormElementValidator> FormElementValidator { get; set; }
    }
}