// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace MCA_EF_API.Domain.Entities
{
    public partial class ChecklistArea
    {
        public ChecklistArea()
        {
            ChecklistType = new HashSet<ChecklistType>();
        }

        public int ChecklistAreaId { get; set; }
        public string Label { get; set; }

        public virtual ICollection<ChecklistType> ChecklistType { get; set; }
    }
}