// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace MCA_EF_API.Domain.Entities
{
    public partial class Form : IAuditable
    {
        public Form()
        {
            FormResponse = new HashSet<FormResponse>();
            FormSection = new HashSet<FormSection>();
        }

        public int FormId { get; set; }
        public Guid FormExternalId { get; set; }
        public int CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public bool IsActive { get; set; }

        public virtual Person CreatedByNavigation { get; set; }
        public virtual ICollection<FormResponse> FormResponse { get; set; }
        public virtual ICollection<FormSection> FormSection { get; set; }
    }
}