// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace MCA_EF_API.Domain.Entities
{
    public partial class FormElementValidator
    {
        public int FormElementValidatorId { get; set; }
        public int FormElementId { get; set; }
        public int TypeValidatorId { get; set; }
        public int? OperatorId { get; set; }
        public string Value { get; set; }

        public virtual FormElement FormElement { get; set; }
        public virtual Operator Operator { get; set; }
        public virtual TypeValidator TypeValidator { get; set; }
    }
}