// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace MCA_EF_API.Domain.Entities
{
    public partial class FormSection : IAuditable
    {
        public FormSection()
        {
            FormElementFormSection = new HashSet<FormElementFormSection>();
            FormElementResponse = new HashSet<FormElementResponse>();
            NestedFormSection = new HashSet<NestedFormSection>();
        }

        public int FormSectionId { get; set; }
        public int FormId { get; set; }
        public string Label { get; set; }
        public string Description { get; set; }
        public int DisplayIndex { get; set; }
        public string LabelColorClass { get; set; }
        public int DisplayRowIndex { get; set; }
        public int DisplayColumnIndex { get; set; }
        public DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public bool IsActive { get; set; }

        public virtual Person CreatedByNavigation { get; set; }
        public virtual Form Form { get; set; }
        public virtual ICollection<FormElementFormSection> FormElementFormSection { get; set; }
        public virtual ICollection<FormElementResponse> FormElementResponse { get; set; }
        public virtual ICollection<NestedFormSection> NestedFormSection { get; set; }
    }
}