// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace MCA_EF_API.Domain.Entities
{
    public partial class NestedFormSection
    {
        public int NestedFormSectionId { get; set; }
        public int ParentFormSectionId { get; set; }
        public int ChildFormSectionId { get; set; }

        public virtual FormSection ParentFormSection { get; set; }
    }
}