// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace MCA_EF_API.Domain.Entities
{
    public partial class TypeFormElement
    {
        public TypeFormElement()
        {
            FormElement = new HashSet<FormElement>();
        }

        public int TypeFormElementId { get; set; }
        public string Label { get; set; }
        public string Description { get; set; }
        public bool AcceptsUserInput { get; set; }

        public virtual ICollection<FormElement> FormElement { get; set; }
    }
}