// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace MCA_EF.Data.Entities.Configurations
{
    public partial class ChecklistAreaConfiguration : IEntityTypeConfiguration<ChecklistArea>
    {
        public void Configure(EntityTypeBuilder<ChecklistArea> entity)
        {
            entity.ToTable("ChecklistArea", "dbo");

            entity.Property(e => e.ChecklistAreaId).HasColumnName("ChecklistAreaID");

            entity.Property(e => e.Label)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ChecklistArea> entity);
    }
}
