// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace MCA_EF.Data.Entities.Configurations
{
    public partial class ChecklistFrequencyConfiguration : IEntityTypeConfiguration<ChecklistFrequency>
    {
        public void Configure(EntityTypeBuilder<ChecklistFrequency> entity)
        {
            entity.ToTable("ChecklistFrequency", "dbo");

            entity.Property(e => e.ChecklistFrequencyId).HasColumnName("ChecklistFrequencyID");

            entity.Property(e => e.Label)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ChecklistFrequency> entity);
    }
}
