// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace MCA_EF.Data.Entities.Configurations
{
    public partial class ResponseValueConfiguration : IEntityTypeConfiguration<ResponseValue>
    {
        public void Configure(EntityTypeBuilder<ResponseValue> entity)
        {
            entity.ToTable("Response_Value", "DynamicForms");

            entity.Property(e => e.TextValue)
                .IsRequired()
                .IsUnicode(false);

            entity.HasOne(d => d.FormElementResponse)
                .WithMany(p => p.ResponseValue)
                .HasForeignKey(d => d.FormElementResponseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Response_Value_FormElement_Response");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ResponseValue> entity);
    }
}
