// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace MCA_EF.Data.Entities.Configurations
{
    public partial class TypeValidatorConfiguration : IEntityTypeConfiguration<TypeValidator>
    {
        public void Configure(EntityTypeBuilder<TypeValidator> entity)
        {
            entity.ToTable("TypeValidator", "DynamicForms");

            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.Label)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TypeValidator> entity);
    }
}
